### ISSUE TITLE
README specifies non-existent version

### ISSUE THREAD

**Issue by brianhenk** [spring-attic/aws-maven#1]
4.0.0.RELEASE does not seem to exist in the public maven repository. 3.0.0.RELEASE worked. Consider updating the README.

**Comment by nebhale** [comment]
Actually the 4.x line is available [via repo.springsource.org](http://repo.springsource.org/simple/libs-release-s3-cache/org/springframework/build/aws-maven), however this isn't ideal.  I'll do the work to get this replicated to central this morning.

**Comment by nebhale** [comment]
Starting with version 4.4.0.RELEASE, this plugin is now published in Maven Central.  You can find it here: http://search.maven.org/#artifactdetails%7Corg.springframework.build%7Caws-maven%7C4.4.0.RELEASE%7Cjar

Let me know if you've got any problems using it.

**Comment by serialx** [comment]
4.5.0.RELEASE does not seem to be released to the central repository. Please have a look.
