### ISSUE TITLE
The readme file should mention the latest release

### ISSUE THREAD

**Issue by jeffmaury** [spring-attic/aws-maven#11]
The readme file mention the 4.4.0.RELEASE version where the latest is 4.8.0.RELEASE

**Comment by nebhale** [comment]
I'm not keen on keeping that value up to date (as it's just supposed to be an example).  Is your objection that people are just going to copy and paste that content into their POM and be done with it?

**Comment by jeffmaury** [comment]
No, my remark was just because this file is the main documentation that users get so having a view on the latest release seems important to me.

**Comment by nebhale** [comment]
Would a link to [this page](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.springframework.build%22%20AND%20a%3A%22aws-maven%22) suffice?

**Comment by jeffmaury** [comment]
Yes, you've got all versions, that's crystal clear
