### ISSUE TITLE
Passphrase is not read if private key is not used in settings.xml

### ISSUE THREAD

**Issue by jmena** [spring-attic/aws-maven#14]
In the settings.xml file, if the privateKey is not set, then the passphrase is ignored.

**Comment by serialx** [comment]
Confirmed, It the plugin breaks on maven 3.1.x because of this. I have to set privateKey to make it work again.

**Comment by koppor** [comment]
The error message is `Canonical string will not be signed, as no AWS Secret Key was provided`. One has to add `<privateKey>${user.home}/.ssh/id_dsa</privateKey>` to settings.xml even if using Windows.

**Comment by BenTels** [comment]
Confirmed, just ran into this issue.

Note that, for me, using password instead of passphrase did not work. The only solution was to set a private key.

**Comment by jmena** [comment]
You can only use the password if you have the patched version.

**Comment by nebhale** [comment]
Complete in the latest snapshot.  I'll get a `5.0.0.RELEASE` out shortly.
