### ISSUE TITLE
Maven 3.1.X breaks this plugin

### ISSUE THREAD

**Issue by florianleibert** [spring-attic/aws-maven#16]
The upload fails b/c maven tries to do a PUT to $maven_s3_folder/

**Comment by cetusteam** [comment]
Can you put the error message of maven -X?

**Comment by brihgt** [comment]
[DEBUG] Using connector WagonRepositoryConnector with priority 0.0 for s3://my-maven-repo/snapshot with username=XXXXXXXXXXXXXXX
Downloading: s3://my-maven-repo/snapshot/com/commons/1.0.0-SNAPSHOT/maven-metadata.xml
[DEBUG] Canonical string will not be signed, as no AWS Secret Key was provided
[DEBUG] Sending Request: GET https://my-maven-repo.s3.amazonaws.com / Parameters: (location: null, ) Headers: (User-Agent: aws-sdk-java/1.4.3 Mac_OS_X/10.9 Java_HotSpot(TM)_64-Bit_Server_VM/20.65-b04-462, Content-Type: application/x-www-form-urlencoded; charset=utf-8, ) 

You can see "Canonical string will not be signed, as no AWS Secret Key was provided". The passphrase is ignored by the plugin. Also, the signature is not in the Headers.
Please see https://github.com/spring-projects/aws-maven/pull/15, jmena has submitted some commits to fix this.

**Comment by nebhale** [comment]
Fixed in the latest snapshot.  I'll get a `5.0.0.RELEASE` out shortly.
