### ISSUE TITLE
First deploy prints stack traces

### ISSUE THREAD

**Issue by brianhenk** [spring-attic/aws-maven#2]
The first deploy to S3 encounters 404s when downloading poms and prints stack traces. 404s should be expected in this situation and handled silently.

**Comment by nebhale** [comment]
I'm almost sure that this has to do with you only being able to see the 3.x releases.  The 4.x line has this [fixed](https://github.com/SpringSource/aws-maven/blob/master/src/main/java/org/springframework/build/aws/maven/SimpleStorageServiceWagon.java#L234-L249).  I'm currently working on issue #1 to make the 4.x line available in Maven Central.
