### ISSUE TITLE
Can't authenticate using settings.xml

### ISSUE THREAD

**Issue by mcacker** [spring-attic/aws-maven#26]
Hi, I have a distribution repo:

```
<distributionManagement>
    <repository>
        <id>aws-release-dev</id>
        <name>AWS Release Repository</name>
        <url>s3://maven-repo-dev/release</url>
    </repository>
    <snapshotRepository>
        <id>aws-snapshot-dev</id>
        <name>AWS Snapshot Repository</name>
        <url>s3://maven-repo-dev/snapshot</url>
    </snapshotRepository>
</distributionManagement>
```

and am attempting to authenticate with corresponding settings.xml server entries:

```
<server>
    <id>aws-release-dev</id>
    <username>xxxx</username>
    <passphrase>yyyyyyyyyyyyyyyy</passphrase>
</server>
<server>
    <id>aws-snapshot-dev</id>
    <username>xxxx</username>
    <passphrase>yyyyyyyyyyyyyyyy</passphrase>
</server>
```

however, these credentials are not being picked up:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project BobScripts: Failed to retrieve remote metadata com.pgi:BobScripts:0.2.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata com.pgi:BobScripts:0.2.1-SNAPSHOT/maven-metadata.xml from/to aws-snapshot-dev (s3://maven-repo-dev/snapshot): Unable to load AWS credentials from any provider in the chain -> [Help 1]

I can only seem to authenticate by specifying the credentials as system properties.

Any ideas?  thanks, Mitchell

**Comment by aaronryden** [comment]
Hey, did you figure out a fix to this @mcacker? Thanks

**Comment by mcacker** [comment]
can't say that I did

**Comment by mstockm** [comment]
@mcacker I think it may be because `<passphrase>` should be `<password>` in your `settings.xml` file.

**Comment by mcacker** [comment]
yes, that was it.  thanks

**Comment by civalue-git** [comment]
Hi,

I have same issue even when putting password instead of passphrase

**Comment by kornha** [comment]
Can someone please clarify exactly what "Id" is supposed to correspond to?
