### ISSUE TITLE
Is this project dormant/dead?

### ISSUE THREAD

**Issue by wnagele** [spring-attic/aws-maven#43]
@spring-buildmaster @spring-issuemaster @nebhale please consider marking this project as dormant/dead if that is the case (it would seem so).

Since it is carried under the Spring "brand" it would seem like a good plugin to use. But in fact it is far behind what users might need these days (see pull requests). This is frustrating.

**Comment by huima** [comment]
+1

**Comment by huima** [comment]
Apparently this is abandaned. I made a fork to Finnish Bradcasting Company repo ( https://github.com/Yleisradio/aws-maven ), where we will update features to the plugin based on our needs. Pullrequests are welcome.

**Comment by mjallday** [comment]
:+1: please either pass this project on or maintain it @nebhale
