### ISSUE TITLE
4.5.0.RELEASE not in repository

### ISSUE THREAD

**Issue by serialx** [spring-attic/aws-maven#5]
4.5.0.RELEASE does not seem to be released to the central repository. Please have a look.

**Comment by nebhale** [comment]
I'll have a look today and see if I can figure out what is going on.

**Comment by nebhale** [comment]
Just wanted to let you know that I'm in the process of troubleshooting a problem with our Artifactory installation pushing to Maven Central.  I don't have an ETA, but I wouldn't expect it to be very long.

**Comment by nebhale** [comment]
So, the recent upgrade to Sonatype's OSS Nexus instance broke the Artifactory push plugin.  I've worked with their support team and found a work around so [4.7.0.RELEASE](http://search.maven.org/#artifactdetails%7Corg.springframework.build%7Caws-maven%7C4.7.0.RELEASE%7Cjar) is now published in central.  Please take a look and let me know if it is accessible for you.
