### ISSUE TITLE
Make artifact and directory permissions customizable

### ISSUE THREAD

**Issue by nebhale** [spring-attic/aws-maven#8]
Currently, all directories and the artifacts uploaded will be given a `PUBLIC_READ` ACL.  In issue #7, it was requested to change the default.  At this point, the default can't be changed without affecting most of the users of the `Wagon`.  This issue should add the ability to configure the ACL to be used on a server by server basis.  I believe that this can be done using the [`settings.xml` `<configuration/>` element](http://maven.apache.org/ref/3.0.5/maven-settings/settings.html#class_server)

**Comment by nebhale** [comment]
@alzadude to address your question from #7 about configuring in Gradle, my working configuration looks something like the following:

``` groovy
uploadArchives {
    configurations {
        deployerJars
    }

    dependencies {
        deployerJars "org.springframework.build:aws-maven:4.7.0.RELEASE"
    }

    repositories.mavenDeployer { deployer ->
        def s3credentials = [:]
        if (project.hasProperty("s3AccessKey")) {
            s3credentials["userName"] = "$s3AccessKey"
        }

        if (project.hasProperty("s3SecretKey")) {
            s3credentials["passphrase"] = "$s3SecretKey"
        }

        configuration = configurations.deployerJars

        repository(url: 's3://<release-repository>') {
            authentication(s3credentials)
        }

        snapshotRepository(url: 's3://<snapshot-repository>') {
            authentication(s3credentials)
        }
    }
}
```

**Comment by nebhale** [comment]
My concern about changing the default is how many projects are already using the default.  Any change there might lead to unexpected behavior.  I'm giving some though to adding the configurability in the 4.x line, bringing forward to a 5.0 and setting the default to `PUBLIC_READ` in 4.x, and nothing in 5.x.  That would allow people who were not prepared for the change to stay on the 4.x line, and the preferred behavior to happen in 5.x.

**Comment by stephankoelle** [comment]
Sounds good.
Here you might find code, how to handle permissions from settings.xml:
https://github.com/jcaddel/maven-s3-wagon/wiki/Permissions

**Comment by cemerick** [comment]
+1; in [Leiningen](http://leiningen.org)-land, we currently do this via https://github.com/technomancy/s3-wagon-private, though that's essentially a hack on top of an old rev of this wagon.  Perhaps it would be reasonable to adopt the `s3p` convention from that work? It makes sense to me that the access control policy of particular bucket "repositories" be represented in their URLs.  Short of that, and without changing any defaults, providing a setter on the concrete wagon impl so that it can be easily customized by other tools would be great.

**Comment by mike10004** [comment]
My fork at https://github.com/mike10004/aws-maven implements a fix for this issue, using "Private" as the default canned ACL for new objects in the bucket. 

Regarding customizable permissions, the implementation for using other canned ACLs is there, but there are no unit tests to show that the specified canned ACL (other than Private) is used. 

Hope this helps.
