### ISSUE TITLE
Use DefaultAWSCredentialsProviderChain to resolve AWS credentials.

### ISSUE THREAD

**Issue by spoon16** [spring-attic/aws-maven#9]
Have you considered using DefaultAWSCredentialsProviderChain from the AWS SDK for resolving AWS credentials?  Right now it will not pick up the active credentials automatically if run on an EC2 instance. DefaultAWSCredentialsProviderChain looks for Environment Variables, System Properties, and then Instance Profile data (set automatically on EC2 instances).

It's simple to implement your own AWSCredentiaProviderChain if you want to include the existing sources that you guys pull credentials from (configuration?).

See: https://github.com/aws/aws-sdk-java/blob/master/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java

**Comment by nebhale** [comment]
Thanks for the tip.  This will be implemented in the `5.x` line.

**Comment by coder17934** [comment]
Could the `com.amazonaws.auth.profile.ProfileCredentialsProvider` be added as well? It is part of the `DefaultAWSCredentialsProviderChain`, but is missing from 68dd7324929cc76de189be753ee5d5ca883fa418.
